name = "aoc"
version = "0.1.0"
gleam = ">= 1.13.0"

[dependencies]
gleam_stdlib = ">= 0.67.0 and < 1.0.0"
question = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
party = ">= 1.0.6 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
advent = { git = "https://github.com/giacomocavalieri/advent.git", ref = "main" }

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
